config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server =>  '/cable'

  root 'store#index'

  get 'categories/:tag', to: 'ads#index', as: :tag
  get 'bookmarks/update'
  get '/messages', to: 'chats#index'
  get '/bookmarks', to: 'bookmarks#index'

  resources :ads
  resources :messages, only: [:create]

  devise_for :users, controllers: {registrations:'registrations'}
  resources :users do
    resources :chats, only: [:index, :show, :create]
  end 
end

app/models/ad.rb
class Ad < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user, optional: true
    acts_as_taggable

    validates :title, :brand, :price, presence: true
    validates :description, length: { maximum: 1000, too_long: "%{count} charactars is the maximum allowed"}
    validates :title, length: { maximum: 140, too_long: "%{count} charactars is the maximum allowed"}
    validates :price, length: { maximum: 10 }

    CONDITION = %w{ New Excellent Mint Used Fair Poor }
    TAG_LIST = %w{ Vehicles Clothes Kids Animals Electronics Furniture Beauty }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :ad
  belongs_to :user
end

app/models/chat.rb
class Chat < ApplicationRecord
    has_many :messages, dependent: :destroy
    has_many :subscriptions, dependent: :destroy
    has_many :users, through: :subscriptions

    validates :identifier, presence: true, uniqueness: true, case_sensitive: false
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :chat
    belongs_to :user
end

app/models/subscription.rb
class Subscription < ApplicationRecord
    belongs_to :chat
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :ads
  has_many :bookmarks
  has_many :messages
  has_many :subscriptions
  has_many :chats, through: :subscriptions

  def existing_chats_users
    existing_chat_users = []
    self.chats.each do |chat|
      existing_chat_users.concat(chat.subscriptions.where.not(user_id: self.id).map {|subscription| subscription.user})
    end
    existing_chat_users.uniq
  end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /ads
  # GET /ads.json
  def index
    if params[:tag]
      @ads = Ad.tagged_with(params[:tag])
    else
      @ads = Ad.all.order("created_at desc")\
    end
  end

  # GET /ads/1
  # GET /ads/1.json
  def show
    @bookmark_exists = Bookmark.where(ad: @ad, user: current_user) == [] ? false : true
    @other_user = @ad.user
  end

  # GET /ads/new
  def new
    @ad = current_user.ads.build
  end

  # GET /ads/1/edit
  def edit
  end

  # POST /ads
  # POST /ads.json
  def create
    @ad = current_user.ads.build(ad_params)

    respond_to do |format|
      if @ad.save
        format.html { redirect_to @ad, notice: 'Ad was successfully created.' }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
     end
    end
  end

  # PATCH/PUT /ads/1
  # PATCH/PUT /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: 'Ad was successfully updated.' }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to ads_url, notice: 'Ad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private

# Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ad_params
      params.require(:ad).permit(:brand, :condition, :title, :description, :price, :image, :tag_list)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def bookmark_text
        return @bookmark_exists ? "Remove Bookmark" : "Bookmark"
    end

    helper_method :bookmark_text
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
    def update
        bookmark = Bookmark.where(ad: Ad.find(params[:ad]), user: current_user)
        if bookmark == []
            Bookmark.create(ad: Ad.find(params[:ad]), user: current_user)
            @bookmark_exists = true
        else
            bookmark.destroy_all
            @bookmark_exists = false
        end
        respond_to do |format|
            format.html {}
            format.js {}
        end
    end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :require_login
    
  def index
    chats = current_user.chats
    @existing_chats_users = current_user.existing_chats_users
  end

  def create
    @other_user = User.find(params[:other_user])
    @chat = find_chat(@other_user) || Chat.new(identifier: SecureRandom.hex)
    if !@chat.persisted?
      @chat.save
      @chat.subscriptions.create(user_id: current_user.id)
      @chat.subscriptions.create(user_id: @other_user.id)
    end
    redirect_to user_chat_path(current_user, @chat,  :other_user => @other_user.id) 
  end

  def show
    chats = current_user.chats
    @existing_chats_users = current_user.existing_chats_users
    @other_user = User.find(params[:other_user])
    @chat = Chat.find_by(id: params[:id])
    @message = Message.new
  end

private

  def find_chat(second_user)
    chats = current_user.chats
    chats.each do |chat|
      chat.subscriptions.each do |s|
        if s.user_id == second_user.id
          return chat
        end
      end
    end
    nil
  end

  def require_login
    redirect_to new_session_path unless user_signed_in?
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    message = Message.new(message_params)
    message.user = current_user
    if message.save
      ActionCable.server.broadcast( "messages_#{message_params[:chat_id]}",
      message: message.content,
      user: message.user.name
      )
    else
      redirect_to chats_path
    end
  end

private

  def message_params
    params.require(:message).permit(:content, :chat_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

private

    def sign_up_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @ads = Ad.all
  end
end

app/helpers/ads_helper.rb
module AdsHelper
    def ad_author(ad)
        user_signed_in? && current_user.id == ad.user_id
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/ads/_form.html.erb
<div class="columns">
  <div class="column is-8 is-centered">
    <%= simple_form_for @ad, html: { multipart: true } do |f| %>    
      <%= f.error_notification %>
      <div class="columns">
        <div class="field column is-9">
          <div class="control">
            <br />
            <%= f.input_field :title , required: true, placeholder: '* Title', class: 'form-control ad-input', wrapper: false %>
          </div>
        </div>
      </div>
      <div class="form-row brandition">
        <div class="col-7">
          <br />
          <%= f.input_field :brand, required: true, placeholder: '* Brand', class: 'form-control brand-ad ad-input', wrapper: false %>
        </div>
        <div class="col">
          <div class="control has-icons-left">
            <br />
            <span class="select">
              <%= f.input_field :condition, collection: Ad::CONDITION, prompt: "Select condition", class: 'form-control condition-ad ad-input' %>
            </span>
            <span class="icon is-small is-left">
              <i class="fa fa-paint-brush"></i>
            </span>
          </div>
        </div>
      </div>
      <br />
      <div class="field">
        <div class="control form-group">
          <%= f.input_field :description, placeholder: 'Description',class: 'form-control desp-ad ad-input', rows: '3', required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
        </div>
      </div>
      <div class="form-row">
        <div class="col">
          <%= f.input :price, required: true, placeholder: 'Price', input_html: { class: "form-control ad-input ad-form-price", maxlength: 10  }, wrapper: false, label_html: { class:"label" } %>
        </div>
        <div class="col-7">
          <div class="control has-icons-left">
            <br />
            <span class="select">
              <%= f.input_field :tag_list, collection: Ad::TAG_LIST, prompt: "Select Category", class: 'form-control ad-input' %>
            </span>
            <span class="icon is-small is-left">
              <i class="fa fa-paint-brush"></i>
            </span>
          </div>
        </div>
      </div>
      <br />
      <div class="custom-file ad-image-div">
        <%= f.input :image, as: :file, type: 'file',id: 'customFile', input_html: { class:"custom-file-input ad-image" }, label: false, wrapper: false %>
        <label class="custom-file-label" for="customFile">Add Images</label>
      </div>
      <br />

      <output id="list"></output>

      <div class="field is-grouped">
        <div class="control">
          <%= f.button :submit, class: 'btn btn-primary ad-submit form-control' %>
        </div>
      </div>

    <% end %>
  </div>
</div>

<script>

document.addEventListener("turbolinks:load", function() {

  var adImage = document.querySelector('.ad-image');

  function handleFileSelect(evt) {
    var files = evt.target.files;
    for (var i = 0, f; f = files[i]; i++) {
      if (!f.type.match('image.*')) {
        continue;
      }
      var reader = new FileReader();
      reader.onload = (function(theFile) {
        return function(e) {
          var span = document.createElement('span');
          span.innerHTML = ['<img class="ad-preview-thumb" src="', e.target.result,
            '" title="', escape(theFile.name), '"/>'
          ].join('');
          document.getElementById('list').insertBefore(span, null);
        };
      })(f);
      reader.readAsDataURL(f);
    }
  }

  if (adImage) {
    this.addEventListener('change', handleFileSelect, false);
  }

});
</script>

app/views/ads/edit.html.erb
<div class="container ad-container">
    <h1 class='ad-h1'>Editing Ad</h1>

    <%= render 'form', ad: @ad %>

    <div class="ad-link">
        <%= link_to 'Back', ads_path, class: 'ad-render-link grey' %>
        <%= link_to 'Cancel', ads_path, class:'ad-render-link red' %>
    </div>
</div>

app/views/ads/index.html.erb
<div class="container ad-index-container">
  
 <!-- <div id="tag_cloud">
    <% tag_cloud Ad.tag_counts, %w[s m l] do |tag, css_class| %>
      <%= link_to tag.name, tag_path(tag.name), class: css_class %>
    <% end %>
  </div>-->
  <%= render 'shared/ads' %>
</div>

app/views/ads/new.html.erb
<div class="container ad-container">
    <h1 class="ad-h1">Create New Ad</h1>

    <%= render 'form', ad: @ad %>

    <div class="ad-link">
        <%= link_to 'Back', ads_path, class: 'ad-render-link grey' %>
        <%= link_to 'Cancel', ads_path, class:'button is-light', class: 'ad-render-link red' %>
    </div>
</div>

app/views/ads/show.html.erb
<section class="ad-show container">
  <div class="row">
    <div class="col-md-6 hit-300 show-col image-col">
      <div class="feature-image">
        <%= cl_image_tag(@ad.image_url(:default)) %>
      </div>
    </div>

    <div class="col-md-6 second-col show-col">
      <div class="jumbotron">
        <h1><%= @ad.title %></h1>
      </div>
      <h3><%= number_to_currency(@ad.price) %></h3>
      <div class="content">
        <div class="show-desp-box">
          <hr>
          <p  class="product-description"><%= @ad.description %></p>
        </div>

        <table class="table is-narrow">

          <% if @ad.condition %>
            <tr>
              <td><strong>Condition:</strong></td>
              <td class="spec"><%= @ad.condition %></td>
            </tr>
          <% end %>

          <% if @ad.brand %>
            <tr>
              <td><strong>Brand:</strong></td>
              <td class="spec"><%= @ad.brand %></td>
            </tr>
          <% end %>
          
          <tr>
            <td><strong>Category:</strong></td>
            <td class="spec"><%= raw @ad.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></td>
          </tr>

          <tr>
            <td><strong>Sold by:</strong></td>
            <td class="spec">
              <% if user_signed_in? %>
                <% if @other_user != current_user %>
                  <%= link_to(user_chats_path(current_user, :other_user => @other_user.id), method: :post) do %>
                  <%= @other_user.name %>
                  <% end %>
                <% else %>
                  You
                <% end %>
              <% else %>
                <%= @ad.user.name %>
              <% end %>
            </td>
          </tr>

        </table>
      </div>
      <div class="bookmark-button">
        <%= link_to bookmark_text, bookmarks_update_path(ad: @ad), id: 'bookmark_link', remote: true %>
        <% if ad_author(@ad) %>
          <%= link_to 'Edit', edit_ad_path(@ad), class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/bookmarks/index.html.erb
<div class="container ad-index-container">
  <% if user_signed_in? %>
    <h1 class="text-center ad-index-header">YOUR BOOKMARKED ADS</h1>

    <div class="ad-index-grid">
      <% current_user.bookmarks.each do |bookmark| %>
        <div class="ad">
          <div class='ad-thumb'>
            <%= link_to cl_image_tag(bookmark.ad.image_url(:thumb)), bookmark.ad %>
            <% if bookmark.ad.condition? %>
              <div class="condition">
                <span><%= bookmark.ad.condition %></span>
              </div>
            <% end %>
          </div>

          <div class="ad-second">
            <h3><%= bookmark.ad.title %></h3>
            <p class="ad-index-soldby">Sold by <%= bookmark.ad.user.name %></p>
            <p class="ad-index-price"><%= number_to_currency(bookmark.ad.price) %></p>
          </div>

        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/bookmarks/update.js.erb
$('#bookmark_link').text("<%= bookmark_text %>");

app/views/chats/index.html.erb
Current Chats:
<ul>
 <% if @existing_chats_users %>
   <% @existing_chats_users.each do |other_user| %>
    <% if other_user != current_user %>
      <li>
        <%= link_to(user_chats_path(current_user, :other_user => other_user.id), method: :post) do %>
        <%= other_user.name %>
        <% end %>
      </li>
     <% end %>
   <% end %>
  <% end %>
</ul>
<!--
All Users:
<ul>
  <% User.all.each do |other_user| %>
   <% if other_user != current_user %>
     <li>
       <%= link_to(user_chats_path(current_user, :other_user => other_user.id), method: :post) do %>
       <%= other_user.name %>
       <% end %>
     </li>
    <% end %>
  <% end %>
</ul>
-->

app/views/chats/show.html.erb
Current Chats:
<ul>
 <% if @existing_chats_users %>
   <% @existing_chats_users.each do |other_user| %>
    <% if other_user != current_user %>
      <li>
        <%= link_to(user_chats_path(current_user, :other_user => other_user.id), method: :post) do %>
        <%= other_user.name %>
        <% end %>
      </li>
     <% end %>
   <% end %>
  <% end %>
</ul>

<div>
    <div>
        <h5>Chat with <%= @other_user.name %></h5>
        <% if @chat.messages.any? %>
            <div id="messages">
                <%= render partial: 'messages/message', collection: @chat.messages.order(id: :asc)%>
            </div>
        <% else %>
            <div id="messages">
            </div>
        <% end %>
    </div>
    <%= render partial: 'messages/message_form', locals: {message: @message, chat: @chat}%>
</div>

<script>
  createMessageChannel();
  messageForm();
</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
  <div class='nav-head'>
    <%= link_to 'Adzwall', root_path, class: 'navbar-brand' %>
  </div>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <span class='navbar-nav cat-section'>
        <li class="nav-item dropdown cat-dropdown">
          <a class="nav-link dropdown-toggle cat-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% tag_cloud Ad.tag_counts, %w[s m l] do |tag| %>
              <%= link_to tag.name, tag_path(tag.name), class: 'dropdown-item' %>
            <% end %>
          </div>
        </li>
      </span>
      <li class="nav-item dropdown header-account">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if user_signed_in? %>
            <%= link_to 'Account Settings', edit_user_registration_path, class: 'dropdown-item' %>
            <%= link_to 'New Ad', new_ad_path, class: 'dropdown-item' %>
            <%= link_to 'Your Bookmarks', '/bookmarks', class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          <% else %>
            <%= link_to 'Sign In', new_user_session_path, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Create Account', new_user_registration_path, class: 'dropdown-item' %>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
  <form class="form-inline my-2 my-lg-0 header-search">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
  </form>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script> 
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Adzwall</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= action_cable_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Catamaran:500&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
   </body>
</html>

app/views/messages/_message.html.erb
<p><%= message.user.name %>: <%= message.content %></p>

app/views/messages/_message_form.html.erb
<%=form_for message, remote: true,authenticity_token: true do |f|%>
  <%= f.text_area :content, data: {textarea: "message"}%>
  <%= f.hidden_field :chat_id, value: chat.id %>
<%end%>

app/views/shared/_ads.html.erb
<h1 class="text-center ad-index-header">LATEST ADS</h1>

<div class="ad-index-grid">
    <% @ads.each do |ad| %>
        <div class="ad">
            <div class='ad-thumb'>
               <% if ad.image.present? %>
                      <%= link_to cl_image_tag(ad.image_url(:thumb)), ad %>
                 <% else %>
                      <%= cl_image_tag('https://res.cloudinary.com/malaika/image/upload/v1573146026/image-placeholder.jpg', class:'img-fluid') %>
                <% end %>
                <% if ad.condition? %>
                    <div class="condition">
                        <span><%= ad.condition %></span>
                    </div>
                <% end %>
            </div>
            <div class="ad-second">
                <h3><%= ad.title %></h3>
                <p class="ad-index-soldby">Sold by <%= ad.user.name %></p>
                <p class="ad-index-price"><%= number_to_currency(ad.price) %></p>
                <p class="ad-index-created"><%= ad.created_at.strftime("%B %d, %Y") %></p>
            </div>
           <!-- <% if ad_author(ad) %>
                <%= link_to "Edit", edit_ad_path(ad), class: 'btn btn-primary' %>
                <%= link_to 'Delete', ad, method: :delete, data: { confirm: 'Are you sure ?'}, class: 'btn btn-primary' %>
            <% end %>-->
        </div>
    <% end %>
</div>

app/views/store/index.html.erb
<div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active" style="object-fit:cover; height: 90vh; background-size: cover; background-position: center; background-image: url('https://res.cloudinary.com/areeba/image/upload/v1578752935/BeFunky-design.jpg')">
      <div class="carousel-caption d-none d-md-block"></div>
    </div>
    <div class="carousel-item" style="object-fit:cover; height: 90vh; background-size: cover; background-position: center; background-image: url('https://res.cloudinary.com/areeba/image/upload/v1579171436/BeFunky-design_1.jpg');">
      <div class="carousel-caption d-none d-md-block"></div>
    </div>
    <div class="carousel-item" style="object-fit: cover; height: 90vh; background-size: 1450px 650px; background-position: center; background-image: url('https://res.cloudinary.com/areeba/image/upload/v1578754394/BeFunky-design-second.jpg');">
      <div class="carousel-caption d-none d-md-block"></div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="container ad-index-container">
  <% if user_signed_in? %>
      <h1 class="text-center ad-index-header">YOUR BOOKMARKED ADS</h1>

      <div class="ad-index-grid">
        <% current_user.bookmarks.each do |bookmark| %>
          <div class="ad">
            <div class='ad-thumb'>
              <%= link_to cl_image_tag(bookmark.ad.image_url(:thumb)), bookmark.ad %>
              <% if bookmark.ad.condition? %>
                <div class="condition">
                  <span><%= bookmark.ad.condition %></span>
                </div>
              <% end %>
            </div>

            <div class="ad-second">
              <h3><%= bookmark.ad.title %></h3>
              <p class="ad-index-soldby">Sold by <%= bookmark.ad.user.name %></p>
              <p class="ad-index-price"><%= number_to_currency(bookmark.ad.price) %></p>
            </div>

          </div>
        <% end %>
      </div>
  <% end %>
  <%= render 'shared/ads' %>
</div>